---
- name: set up vagrant host
  hosts: all
  become: true
  collections:
    - pandemonium1986.k8s_toolbox
  environment:
    REQUESTS_CA_BUNDLE: '/etc/pki/tls/certs/ca-bundle.crt'
  tasks:
    - debug:
        msg: "{{ ansible_distribution_release }}"
      tags: debug

    - name: "Add {{ username }} group"
      group:
        name: "{{ username }}"

    - name: "Add {{ username }} user"
      user:
        generate_ssh_key: yes
        group: "{{ username }}" 
        name: "{{ username }}"

    - name: "Allow {{ username }} group to have passwordless sudo"
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%{{ username }}'
        line: '%{{ username }} ALL=(ALL) NOPASSWD: ALL'
        validate: visudo -cf %s

    # - name: "Add repos"
    #   yum_repository:
    #     name: "{{ item.name }}"
    #     baseurl: "{{ item.baseurl }}"
    #     description: "{{ item.description }}"
    #   loop: "{{ repos }}"

    - name: "Add all the packages"
      dnf:
        name: "{{ packages }}"

    - import_role:
        name: jaredzieche.sshuttle
      vars:
        sshuttle_user: "{{ username }}"
        sshuttle_group: "{{ username }}"
    - import_role:
        name: geerlingguy.nodejs
      tags: nodejs
    - import_role:
        name: christiangda.awscli
      tags: awscli
    - import_role:
        name: minikube
      tags: minikube
    - import_role:
        name: kubectx
      tags: kubectx
    - import_role:
        name: k9s
      tags: k9s
    - import_role:
        name: stern
      tags: stern
    - import_role:
        name: helm
      tags: helm