- name: add required yum repos
  yum_repository:
    name: "{{ item.name }}"
    baseurl: "{{ item.baseurl }}"
    file: external_repos
    gpgkey: "{{ item.gpgkey | default(omit) }}"
  loop: "{{ yum_repos }}"

- name: install required packages
  yum:
    state: latest
    name: "{{ yum.packages }}"
    enablerepo: "{{ yum_repos }}"
