repos:
  - name: kubernetes
    baseurl: "https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64"
    gpgkey:
      - "https://packages.cloud.google.com/yum/doc/yum-key.gpg"
      - "https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"
  - name: hashicorp
    baseurl: "https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo"
    gpgkey: 
  - name: epel
    baseurl: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm"
    gpgkey:
packages:
    - curl
    - wget
    - git
    - tmux
    - firefox
    - xvfb
    - vim
    - nvim
    - yum-utils
    - kubectl
    - helm3
    - packer
    - terraform
    - vault
    - awscli
    - python3
    - boto3
    - jq
    - yq