# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'

current_dir    = File.dirname(File.expand_path(__FILE__))
configs        = YAML.load_file("#{current_dir}/vagrant_config.yaml")
vagrant_config = configs['configs'][configs['configs']['use']]

Vagrant.configure("2") do |config|
  config.ssh.insert_key = true
  config.vm.box = "builds/virtualbox-rhel8.box"
  config.vm.box_url = vagrant_config['box_url']
  config.ssh.password = "vagrant"
  config.vm.synced_folder "shared/ansible/roles/", "/vagrant/shared/ansible/roles", disabled: true
  # VirtualBox.
  config.vm.define "virtualbox" do |virtualbox|
    virtualbox.vm.hostname = "virtualbox-rhel8"
    virtualbox.vm.network :private_network, ip: "10.10.2.15"
    config.vm.provider :virtualbox do |v|
      v.gui = true
      v.memory = 2048
      v.cpus = 1
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--ioapic", "on"]
      v.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
      v.customize ["modifyvm", :id, "--vram", "128"]
    end
    config.vm.provision "shell", inline: "echo Hello, World"
    config.vm.provision "shell", path: "setup.sh"
    config.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "shared/ansible/vagrant_main.yml"
      ansible.galaxy_role_file = "shared/ansible/vagrant_requirements.yml"
      ansible.galaxy_command = "ansible-galaxy install --role-file=%{role_file} --force"
      ansible.extra_vars = {
        username: vagrant_config['username']
      }
    end
  end
end