# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = true
  config.vm.box = "builds/virtualbox-rhel8.box"
  config.vm.box_url = "file:///C:/Users/VHACHAZiechJ/gitpub/boxes/RHEL8/builds/virtualbox-rhel8.box"
  config.ssh.password = "vagrant"
  # VirtualBox.
  config.vm.define "virtualbox" do |virtualbox|
    virtualbox.vm.hostname = "virtualbox-rhel8"
    virtualbox.vm.network :private_network, ip: "10.10.2.15"
    config.vm.provider :virtualbox do |v|
      v.gui = true
      v.memory = 2048
      v.cpus = 1
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--ioapic", "on"]
      v.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
      v.customize ["modifyvm", :id, "--vram", "128"]
    end
    config.vm.provision "shell", inline: "echo Hello, World"
    config.vm.provision "shell", path: "setup.sh"
    config.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "shared/ansible/vagrant_main.yml"
      ansible.galaxy_role_file = "shared/ansible/vagrant_requirements.yml"
    end
  end
end